### ISSUE TITLE
Manage page can be slow to load

### ISSUE THREAD

**Issue by twinser** [Stub-O-Matic/stubo-app#40] opened 2015-05-22 12:59 UTC
The manage page is often slow to load. The more scenarios stored in Stubo across the cluster, the slower the page is to load, however, the page is known to be slow even when there are only a few stubs loaded. This is causing user complaints :disappointed: 

What can we do to speed this up? Ideas on the back of a postcard please. :postbox:

**Comment by johnecobo** [comment] 2015-05-22 13:11
Can you quantify the problem? The AWS based test environment has 100 scenarios on /manage which loaded for me in 23 seconds. How does that compare with the slow examples? See if you can reproduce the issue on AWS, if not, it narrows the scope of the problem a bit.

**Comment by twinser** [comment] 2015-05-22 13:40
Would you not consider 23 seconds to be slow? In contrast, the tracker page takes less than a second to load for 100 records. In comparison to the rest of the pages load times, it is much slower.

I have just timed how long it took to load the manage page on one of our production clusters and 65 scenarios took 61 seconds to load. It must be down to more than just how many there are.

What is going on to make this page take a longer time, but the tracker goes quickly for what seems like a similar operation?

**Comment by johnecobo** [comment] 2015-05-22 13:49
We put indexes on Mongo specifically for the tracker page. The same needs to be done for /manage. Give O.C. a target load time such as 3 seconds for the perf data on AWS /manage so they have a something to aim for. If there is something massively different in our real data than the perf test scenarios use that for the target - provided we can reproduce the data for proving the improvement.

**Comment by twinser** [comment] 2015-05-22 13:55
Seems like a reasonable target to me :+1: I can't imagine the real data is massively different.

**Comment by guyrichardson** [comment] 2015-06-16 14:22
The performance of this page will be investigated based on this feedback.
Any SLA/target load time will need to be agreed through the BA support channel (rather than through GitHub)

**Comment by rusenask** [comment] 2015-07-07 16:28
Should load quickly after https://github.com/Stub-O-Matic/stubo-app/pull/68 merged and deployed

**Comment by JohnFDavenport** [comment] 2015-07-10 08:05
:+1: @rusenask and @twinser

**Comment by twinser** [comment] 2015-07-13 07:45
:+1: :+1: :+1: Great news :smiley:

**Comment by rusenask** [comment] 2015-07-13 15:02
Just posting this from mailing thread for more transparency:
The question was: "I am interested in how OC have tested that the results."
Answer:
I have tested it locally. At first, I replicated the problem in my testing environment having 5 scenarios with 130 megabytes of stubs. Then, activated profiling and checked what is slowing down the stubo.
I have found five major problems in /manage page algorithm:
	1. It was looping through session list, getting scenario and then for each scenario it was fetching stubs, however the stub scenario name wasn’t indexed so that took some time.
	2. Going through a stub list of each scenario requires a lot of cpu time and no multiprocessing was used for that approach. It also used quite a lot of traffic cause upon every manage page request it will be downloading all stubs from MongoDB to Stubo.
	3. It was doing it (2) twice - first time to get dates and the second time to accumulate space used.
	4. To get space used value it was calling len(unicode(stub.payload)) on each stub, so imagine downloading 100 megabytes of stubs and then calling len() on all of them. 
	5. All of these operations have significant impact on server performance since they are cpu, network and memory heavy.
I have changed approach:
	1. Store stub space_used value as integer during stub creation or update it if the response body is extended.
	2. During the /manage page request - use mongo aggregation framework to get stats for all scenarios at once (https://github.com/Stub-O-Matic/stubo-app/blob/develop/stubo/model/db.py#L83-L161) and form a dictionary where values can be accessed instantly. No looping through large list or something similar is required. Pythonic - complex is better than complicated :) 

Loading time for me was reduced from 5.5 seconds to 70 ms. You should have similar results, loading time will probably be lower than 100 ms, depending on network.

**Closed** 2015-07-24 10:02 UTC
Labels: released
